### ISSUE TITLE
Tests that demonstrate table-level permissions

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-edit-schema#59]
I built this for:
- #22

But in writing the release notes (#58) I realized the tests don't actually cover this yet. The documentation should mention it too.

**Comment by simonw** [comment]
I first did a round of manual testing:
```bash
sqlite-utils create-database sales.db
sqlite-utils create-database marketing.db
sqlite-utils create-table sales.db notes id integer --pk id
sqlite-utils create-table sales.db customers id integer --pk id
datasette -c perms.yml sales.db marketing.db --secret 1 --reload
```
Where `perms.yml` contained:
```yaml
databases:
  marketing:
    permissions:
      create-table:
        id: pelican
      drop-table:
        id: pelican
      alter-table:
        id: pelican
  sales:
    tables:
      notes:
        permissions:
          alter-table:
            id: pelican
```
And I used a new `datasette-unsafe-actor-debug` plugin to help test.

This worked, though it did show me I need to fix this:
- #60
